# goreleaser.yaml
project_name: tlm
release:
  github:
    owner: yusufcanb
    name: tlm
builds:
  - id: "tlm"
    main: ./main.go
    binary: tlm
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.sha1ver={{.ShortCommit}}
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
